name: Deploy Kubernetes Cluster using Kubeadm and AWS EC2s

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      master_node_ip: ${{ steps.apply.outputs.master_node_ip }}
      worker_node_ip: ${{ steps.apply.outputs.worker_node_ip }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      id: apply
      run: terraform apply -auto-approve

    # Optional destroy step
    - name: Destroy Terraform resources
      run: terraform destroy -auto-approve
